# Generated by Django 5.2.2 on 2025-06-04 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ('name',),
                'permissions': [('can_create_currency', 'Can create currency'), ('can_edit_currency', 'Can edit currency'), ('can_delete_currency', 'Can delete currency')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/%Y/%m/%d/')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
                'permissions': [('can_create_category', 'Can create category'), ('can_edit_category', 'Can edit category'), ('can_delete_category', 'Can delete category')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item/%Y/%m/%d/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detail', models.TextField(blank=True, null=True)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item', to='menu.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item', to='menu.currency')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('can_create_item', 'Can create item'), ('can_edit_item', 'Can edit item'), ('can_delete_item', 'Can delete item')],
            },
        ),
    ]
