# Generated by Django 5.2.2 on 2025-06-06 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'permissions': [('can_create_category', 'Can create category'),
                                                            ('can_edit_category', 'Can edit category'),
                                                            ('can_delete_category', 'Can delete category'),
                                                            ('can_view_category', 'Can view category')],
                     'verbose_name_plural': 'Categories'},
        ),
    ]
