# Generated by Django 5.2.2 on 2025-06-09 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'permissions': [('can_create_category', 'Can create category'),
                                                            ('can_edit_category', 'Can edit category'),
                                                            ('can_delete_category', 'Can delete category')],
                     'verbose_name_plural': 'Categories'},
        ),
    ]
