# Generated by Django 5.2.2 on 2025-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
